# Generated by Django 6.1 on 2026-08-19 23:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id_secteur', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_etablissement',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id_quartier', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id_commune', models.ForeignKey(db_column='id_commune', on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='health.commune')),
            ],
            options={
                'db_table': 'quartier',
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id_population', models.AutoField(primary_key=True, serialize=False)),
                ('effectif', models.IntegerField()),
                ('pop_masculine', models.IntegerField()),
                ('pop_feminine', models.IntegerField()),
                ('id_quartier', models.ForeignKey(db_column='id_quartier', on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='health.quartier')),
            ],
            options={
                'db_table': 'population',
            },
        ),
        migrations.CreateModel(
            name='EtablissementSante',
            fields=[
                ('id_etablissement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_quartier', models.ForeignKey(db_column='id_quartier', on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='health.quartier')),
                ('id_secteur', models.ForeignKey(blank=True, db_column='id_secteur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='health.secteur')),
                ('id_type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='health.typeetablissement')),
            ],
            options={
                'db_table': 'etablissement_sante',
            },
        ),
    ]
